# Generated by Django 4.1.5 on 2023-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ByteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=" &#9679; 'description'. &#9679; 'description'. &#9679; 'description'. ", max_length=200),
        ),
    ]
